import { ExecutionContext, ForbiddenException } from '@nestjs/common';
import { RoleCode } from '../enums/role.enum';
import { AuthenticatedUser } from '../interfaces/authenticated-user.interface';

/** Reviewed HTTP permissions. null is an explicitly public trust boundary.
 * Unknown routes fail closed; update this policy when introducing an API. */
export const ACCESS_POLICY: Readonly<
  Record<string, readonly RoleCode[] | null>
> = {
  'AppController.getHello': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AppointmentsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AppointmentsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AppointmentsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AppointmentsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AppointmentsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AuditLogsController.list': [RoleCode.SUPER_ADMIN],
  'AuditLogsController.findOne': [RoleCode.SUPER_ADMIN],
  'AuthController.login': null,
  'AuthController.register': null,
  'AuthController.sendOtp': null,
  'AuthController.verifyOtp': null,
  'AuthController.refresh': null,
  'AuthController.logout': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'AuthController.me': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillDocumentsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillDocumentsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillDocumentsController.createDownloadUrl': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillDocumentsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillDocumentsController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillsController.membershipOffers': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillsController.validateCoupon': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'BillsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'BillsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'CampaignsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.publish': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CampaignsController.cancel': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'CustomerAddressesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomerAddressesController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomerAddressesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomerAddressesController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomerAddressesController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomersController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomersController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'CustomersController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomersController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'CustomersController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpensesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpensesController.summary': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpensesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpensesController.create': [RoleCode.ADMIN, RoleCode.MANAGER],
  'ExpensesController.update': [RoleCode.ADMIN, RoleCode.MANAGER],
  'ExpenseCategoriesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpenseCategoriesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ExpenseCategoriesController.create': [RoleCode.ADMIN],
  'ExpenseCategoriesController.update': [RoleCode.ADMIN],
  'ExpenseCategoriesController.status': [RoleCode.ADMIN],
  'FranchiseSubscriptionsController.list': [RoleCode.SUPER_ADMIN],
  'FranchiseSubscriptionsController.enroll': [RoleCode.SUPER_ADMIN],
  'FranchiseSubscriptionsController.me': [
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'FranchiseSubscriptionsController.request': [
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'FranchiseSubscriptionsController.cancel': [RoleCode.SUPER_ADMIN],
  'FranchisesController.list': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'FranchisesController.create': [RoleCode.SUPER_ADMIN],
  'FranchisesController.findOne': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'FranchisesController.update': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'FranchisesController.updateStatus': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'HealthController.check': null,
  'InventoryController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'InventoryController.listMovements': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'InventoryController.adjust': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'InventoryController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'InventoryController.listMovementsForInventory': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'LoyaltyController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'LoyaltyController.balance': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'LoyaltyController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'LoyaltyController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MediaObjectsController.upload': null,
  'MediaObjectsController.download': null,
  'MediaController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MediaController.createUpload': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'MediaController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MediaController.confirm': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'MediaController.createDownloadUrl': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MediaController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'ProfilePhotosController.get': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProfilePhotosController.initialize': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProfilePhotosController.upload': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProfilePhotosController.finalize': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProfilePhotosController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProfileAvatarController.display': null,
  'MembershipPlansController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MembershipPlansController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'MembershipPlansController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MembershipPlansController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'MembershipPlansController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'MembershipsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MembershipsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'MembershipsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'MembershipsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'MembershipsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'NotificationsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'NotificationsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'NotificationsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'NotificationsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PaymentsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'PaymentsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PaymentsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'PaymentsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PlatformPlansController.list': [RoleCode.SUPER_ADMIN],
  'PlatformPlansController.create': [RoleCode.SUPER_ADMIN],
  'PlatformPlansController.findOne': [RoleCode.SUPER_ADMIN],
  'PlatformPlansController.update': [RoleCode.SUPER_ADMIN],
  'PlatformPlansController.updateStatus': [RoleCode.SUPER_ADMIN],
  'AdminReportsController.analytics': [RoleCode.ADMIN],
  'AdminReportsController.history': [RoleCode.ADMIN],
  'AdminReportsController.generate': [RoleCode.ADMIN],
  'AdminReportsController.download': [RoleCode.ADMIN],
  'PlatformReportsController.list': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.analyticsSection': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.filterOptions': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.generate': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.findOne': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.download': [RoleCode.SUPER_ADMIN],
  'PlatformReportsController.remove': [RoleCode.SUPER_ADMIN],
  'ProductCategoriesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProductCategoriesController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductCategoriesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProductCategoriesController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductCategoriesController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductVendorsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'ProductVendorsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductVendorsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductVendorsController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProductsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ProductsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ProductsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'PurchasesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PurchasesController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PurchasesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PurchasesController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'PurchasesController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'RolesController.findAll': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'RolesController.findOne': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'SalonPhotosController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'SalonPhotosController.createUpload': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonPhotosController.upload': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonPhotosController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonPhotosController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonPhotosController.remove': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'SalonsController.listPicker': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'SalonsController.create': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'SalonsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'SalonsController.update': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'SalonsController.updateLocation': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SalonsController.updateStatus': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'SalonsController.geocode': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'SearchController.search': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ServiceCategoriesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ServiceCategoriesController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServiceCategoriesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ServiceCategoriesController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServiceCategoriesController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServicesController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ServicesController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServicesController.bulkCreate': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServicesController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
    RoleCode.CUSTOMER,
  ],
  'ServicesController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'ServicesController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SettingsController.getMaintenanceStatus': null,
  'SettingsController.getGeneral': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateGeneral': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateBranding': [RoleCode.SUPER_ADMIN],
  'SettingsController.createLogoUpload': [RoleCode.SUPER_ADMIN],
  'SettingsController.createFaviconUpload': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateMaintenance': [RoleCode.SUPER_ADMIN],
  'SettingsController.getSecurity': [RoleCode.SUPER_ADMIN],
  'SettingsController.updatePasswordPolicy': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateSession': [RoleCode.SUPER_ADMIN],
  'SettingsController.getLogRetention': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateLogRetention': [RoleCode.SUPER_ADMIN],
  'SettingsController.purgeExpiredLogs': [RoleCode.SUPER_ADMIN],
  'SettingsController.listLogs': [RoleCode.SUPER_ADMIN],
  'SettingsController.clearCache': [RoleCode.SUPER_ADMIN],
  'SettingsController.resetSettings': [RoleCode.SUPER_ADMIN],
  'SettingsController.createBackup': [RoleCode.SUPER_ADMIN],
  'SettingsController.listBackups': [RoleCode.SUPER_ADMIN],
  'SettingsController.restoreBackup': [RoleCode.SUPER_ADMIN],
  'SettingsController.getEmail': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateEmail': [RoleCode.SUPER_ADMIN],
  'SettingsController.testEmail': [RoleCode.SUPER_ADMIN],
  'SettingsController.getNotifications': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateNotifications': [RoleCode.SUPER_ADMIN],
  'SettingsController.checkSystemUpdate': [RoleCode.SUPER_ADMIN],
  'SettingsController.getSystem': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateSystem': [RoleCode.SUPER_ADMIN],
  'SettingsController.listIntegrations': [RoleCode.SUPER_ADMIN],
  'SettingsController.createIntegration': [RoleCode.SUPER_ADMIN],
  'SettingsController.updateIntegration': [RoleCode.SUPER_ADMIN],
  'SettingsController.deleteIntegration': [RoleCode.SUPER_ADMIN],
  'SettingsController.listActivity': [RoleCode.SUPER_ADMIN],
  'SupportTicketsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SupportTicketsController.create': [RoleCode.ADMIN, RoleCode.MANAGER],
  'SupportTicketsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'SupportTicketsController.updateStatus': [RoleCode.SUPER_ADMIN],
  'UsersController.list': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'UsersController.create': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'UsersController.findOne': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'UsersController.update': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'UsersController.updateStatus': [RoleCode.SUPER_ADMIN, RoleCode.ADMIN],
  'VendorsController.list': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'VendorsController.create': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'VendorsController.findOne': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
    RoleCode.STAFF,
  ],
  'VendorsController.update': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
  'VendorsController.updateStatus': [
    RoleCode.SUPER_ADMIN,
    RoleCode.ADMIN,
    RoleCode.MANAGER,
  ],
};
export function permissionKey(context: ExecutionContext): string {
  return `${context.getClass().name}.${context.getHandler().name}`;
}
export function isPublicPermission(key: string): boolean {
  return Object.hasOwn(ACCESS_POLICY, key) && ACCESS_POLICY[key] === null;
}
export function assertPermission(
  user: AuthenticatedUser | undefined,
  key: string,
): void {
  const roles = ACCESS_POLICY[key];
  if (!roles || !user || !roles.includes(user.role)) {
    throw new ForbiddenException('Insufficient permission for this operation');
  }
}
export function assertFinancialAuthority(user: AuthenticatedUser): void {
  if (
    ![RoleCode.SUPER_ADMIN, RoleCode.ADMIN, RoleCode.MANAGER].includes(
      user.role,
    )
  ) {
    throw new ForbiddenException(
      'Financial overrides require an administrator or manager',
    );
  }
}
