'use client';
import { formatDateTime } from '@/lib/format';
import { Download, FileSpreadsheet, FolderOpen } from 'lucide-react';
import type { AdminGeneratedReport } from '../../services/admin-reports.service';
import { AdminReportPanel, reportDate } from './admin-report-panel';
type Props = {
  reports: AdminGeneratedReport[];
  loading: boolean;
  error: boolean;
  onRetry: () => void;
  onDownload: (report: AdminGeneratedReport) => void;
  disabled: boolean;
};
export function AdminReportHistory({
  reports,
  loading,
  error,
  onRetry,
  onDownload,
  disabled,
}: Props) {
  const layout =
    'grid min-w-0 gap-x-5 gap-y-3 content-lg:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)_minmax(0,1fr)_minmax(0,1fr)_auto]';
  return (
    <AdminReportPanel
      title="Generated reports"
      description="Your latest 20 exports, saved with their original data and filters"
      action={
        <span className="rounded-full bg-muted px-3 py-1 text-xs font-medium text-text-secondary">
          {reports.length} saved
        </span>
      }
    >
      {loading ? (
        <p role="status" className="py-8 text-sm text-text-secondary">
          Loading reports...
        </p>
      ) : error ? (
        <p role="alert" className="py-8 text-sm text-red-600">
          Unable to load report history.{' '}
          <button
            type="button"
            onClick={onRetry}
            className="font-medium underline"
          >
            Try again
          </button>
        </p>
      ) : !reports.length ? (
        <div className="flex flex-col items-center rounded-xl border border-dashed border-border py-10 text-center">
          <FolderOpen className="mb-3 size-8 text-champagne" aria-hidden />
          <p className="text-sm font-medium text-text">
            No reports generated yet
          </p>
          <p className="mt-1 text-xs text-text-secondary">
            Choose your filters and download your first Excel report.
          </p>
        </div>
      ) : (
        <div>
          <div
            className={`${layout} mb-1 hidden border-b border-border pb-3 text-[11px] font-semibold uppercase tracking-wide text-text-secondary content-lg:grid`}
            aria-hidden
          >
            <span>Report</span>
            <span>Date range</span>
            <span>Branch</span>
            <span>Generated by</span>
            <span className="w-32 text-right">Download</span>
          </div>
          <div className="divide-y divide-border">
            {reports.map((report) => (
              <article
                key={report.id}
                className={`${layout} items-center py-5 text-sm [overflow-wrap:anywhere]`}
              >
                <div className="flex min-w-0 items-start gap-3">
                  <span className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30">
                    <FileSpreadsheet className="size-5" aria-hidden />
                  </span>
                  <div className="min-w-0">
                    <h3 className="font-semibold text-text">{report.name}</h3>
                    <div className="mt-1.5 flex flex-wrap items-center gap-2 text-xs">
                      <span className="text-text-secondary">Excel (.xlsx)</span>
                      <span
                        className={`rounded-full px-2 py-0.5 font-medium ${report.status === 'Ready' ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-950/30' : report.status === 'Failed' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'}`}
                      >
                        {report.status}
                      </span>
                    </div>
                  </div>
                </div>
                <div>
                  <span className="mb-1 block text-[11px] text-text-secondary content-lg:hidden">
                    Date range
                  </span>
                  <p className="text-xs leading-relaxed text-text-secondary">
                    {reportDate(report.dateFrom)}
                    <br />
                    {reportDate(report.dateTo)}
                  </p>
                </div>
                <div>
                  <span className="mb-1 block text-[11px] text-text-secondary content-lg:hidden">
                    Branch
                  </span>
                  <p className="text-xs leading-relaxed text-text">
                    {report.branch}
                  </p>
                </div>
                <div className="text-xs">
                  <p className="font-medium text-text">{report.generatedBy}</p>
                  <p className="mt-1 text-text-secondary">
                    {formatDateTime(report.generatedOn)}
                  </p>
                </div>
                <button
                  type="button"
                  onClick={() => onDownload(report)}
                  disabled={disabled || report.status !== 'Ready'}
                  className="flex min-h-10 w-fit items-center gap-2 rounded-lg border border-border px-3 text-xs font-semibold text-text transition hover:border-champagne hover:bg-champagne-light disabled:opacity-50"
                >
                  <Download className="size-3.5" aria-hidden />
                  Download Excel
                </button>
              </article>
            ))}
          </div>
        </div>
      )}
    </AdminReportPanel>
  );
}
