'use client';
import { Button } from '@/components/ui/button';
import { StatusBadge } from '@/components/ui/status-badge';
import { formatDateTime } from '@/lib/format';
import {
  useDownloadReport,
  useGenerateReport,
} from '../hooks/use-report-mutations';
import type { PaginationMeta, ReportListRow } from '../types/reports.types';
import { AnalyticsState, AnalyticsTable } from './report-analytics-widgets';
import { ReportsPagination } from './reports-pagination';
export function ReportsTable({
  rows,
  meta,
  isLoading = false,
  isError = false,
  onRetry,
  onPageChange,
  onView,
}: {
  rows: ReportListRow[];
  meta: PaginationMeta;
  isLoading?: boolean;
  isError?: boolean;
  onRetry?: () => void;
  onPageChange: (page: number) => void;
  onView: (row: ReportListRow) => void;
}) {
  const download = useDownloadReport(),
    regenerate = useGenerateReport();
  const mapped = rows.map((row) => ({
    id: row.id,
    name: row.name,
    type: row.typeLabel,
    scope: [
      row.franchiseName ?? 'All Franchises',
      row.salonName ?? 'All Salons',
    ].join(' · '),
    range: row.dateRangeLabel,
    date: formatDateTime(row.generatedOn),
    by: row.generatedBy,
    format: 'Excel (.xlsx)',
    status: 'Generated',
  }));
  return (
    <AnalyticsState
      loading={isLoading}
      error={isError}
      retry={() => onRetry?.()}
    >
      <div className="space-y-0">
        <AnalyticsTable
          title="Generated Reports"
          data={mapped}
          empty="No reports match these filters. Generate a report to see it here."
          columns={[
            { key: 'name', label: 'Report name' },
            { key: 'type', label: 'Type' },
            { key: 'scope', label: 'Scope' },
            { key: 'range', label: 'Date range' },
            { key: 'date', label: 'Generated on' },
            { key: 'by', label: 'Generated by' },
            { key: 'format', label: 'Format' },
            {
              key: 'status',
              label: 'Status',
              render: () => (
                <StatusBadge
                  label="Generated"
                  tone="success"
                  className="max-w-full whitespace-normal px-2 text-[0.625rem]"
                />
              ),
            },
            {
              key: 'actions',
              label: 'Actions',
              render: (value) => {
                const row = rows.find((r) => r.id === value.id)!;
                return (
                  <div className="flex flex-wrap gap-1">
                    <Button
                      className="max-w-full whitespace-normal px-2 text-xs"
                      size="sm"
                      variant="outline"
                      onClick={() => onView(row)}
                    >
                      View
                    </Button>
                    <Button
                      className="max-w-full whitespace-normal px-2 text-xs"
                      size="sm"
                      variant="outline"
                      disabled={download.isPending}
                      onClick={() =>
                        download.mutate({ id: row.id, name: row.name })
                      }
                    >
                      Download
                    </Button>
                    <Button
                      className="max-w-full whitespace-normal px-2 text-xs"
                      size="sm"
                      variant="outline"
                      disabled={regenerate.isPending}
                      title="Create a fresh snapshot of this report’s original date range and scope"
                      onClick={() =>
                        regenerate.mutate({
                          type: row.type,
                          format: 'excel',
                          dateFrom: row.dateFrom,
                          dateTo: row.dateTo,
                          ...(row.franchiseId
                            ? { franchiseId: row.franchiseId }
                            : {}),
                          ...(row.salonId ? { salonId: row.salonId } : {}),
                          salonSort:
                            row.snapshot.salonSort === 'transactions' ||
                            row.snapshot.salonSort === 'customers' ||
                            row.snapshot.salonSort === 'averageBill'
                              ? row.snapshot.salonSort
                              : 'revenue',
                          serviceSort:
                            row.snapshot.serviceSort === 'quantity' ||
                            row.snapshot.serviceSort === 'transactions'
                              ? row.snapshot.serviceSort
                              : 'revenue',
                          interval:
                            row.snapshot.interval === 'day' ||
                            row.snapshot.interval === 'week' ||
                            row.snapshot.interval === 'year'
                              ? row.snapshot.interval
                              : 'month',
                        })
                      }
                    >
                      Regenerate
                    </Button>
                  </div>
                );
              },
            },
          ]}
        />
        <ReportsPagination meta={meta} onPageChange={onPageChange} />
      </div>
    </AnalyticsState>
  );
}
