'use client';

import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Building2,
  CreditCard,
  Download,
  FileSpreadsheet,
  FileText,
  IndianRupee,
  MoreVertical,
  Tags,
  Users,
} from 'lucide-react';

import {
  SectionEmptyState,
  SectionErrorState,
} from '@/components/layout/section-states';
import { Skeleton } from '@/components/ui/skeleton';
import { StatusBadge } from '@/components/ui/status-badge';
import { formatDateTime } from '@/lib/format';
import type {
  PaginationMeta,
  ReportListRow,
  ReportType,
} from '../types/reports.types';
import { ReportsPagination } from './reports-pagination';

type ReportsTableProps = {
  rows: ReportListRow[];
  meta: PaginationMeta;
  isLoading?: boolean;
  isError?: boolean;
  onRetry?: () => void;
  onPageChange: (page: number) => void;
};

const TYPE_ICONS: Record<ReportType, LucideIcon> = {
  financial: IndianRupee,
  business: Building2,
  user: Users,
  transaction: CreditCard,
  subscription: Tags,
  activity: Activity,
};

function typeTone(
  type: ReportType,
): 'success' | 'warning' | 'danger' | 'neutral' | 'accent' | 'info' {
  if (type === 'financial') return 'success';
  if (type === 'business') return 'accent';
  if (type === 'user') return 'info';
  if (type === 'transaction') return 'warning';
  if (type === 'subscription') return 'neutral';
  return 'neutral';
}

export function ReportsTable({
  rows,
  meta,
  isLoading,
  isError,
  onRetry,
  onPageChange,
}: ReportsTableProps) {
  return (
    <div className="app-surface-card overflow-hidden" data-dash-animate="section">
      {isLoading ? (
        <div className="space-y-3 p-5">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-14 w-full rounded-lg" />
          ))}
        </div>
      ) : isError ? (
        <SectionErrorState
          message="We could not load reports. Please try again."
          onRetry={onRetry}
        />
      ) : rows.length === 0 ? (
        <SectionEmptyState
          title="No reports yet"
          message="Generated reports will appear here once report generation is available."
        />
      ) : (
        <>
          <div className="hidden overflow-x-auto lg:block">
            <table className="w-full min-w-[920px] text-left text-sm">
              <thead className="border-b border-border bg-ivory/80 text-xs font-semibold uppercase tracking-wide text-text-secondary">
                <tr>
                  <th className="px-5 py-3 font-semibold">Report Name</th>
                  <th className="px-5 py-3 font-semibold">Type</th>
                  <th className="px-5 py-3 font-semibold">Date Range</th>
                  <th className="px-5 py-3 font-semibold">Generated On</th>
                  <th className="px-5 py-3 font-semibold">Generated By</th>
                  <th className="px-5 py-3 font-semibold">Format</th>
                  <th className="px-5 py-3 font-semibold">
                    <span className="sr-only">Actions</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => {
                  const TypeIcon = TYPE_ICONS[row.type];
                  const FormatIcon =
                    row.format === 'excel' ? FileSpreadsheet : FileText;
                  return (
                    <tr
                      key={row.id}
                      className="border-b border-border last:border-0 hover:bg-ivory/60"
                    >
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-3">
                          <span className="inline-flex size-10 items-center justify-center rounded-full bg-champagne-light text-champagne">
                            <TypeIcon className="size-4" aria-hidden />
                          </span>
                          <div className="min-w-0">
                            <p className="font-semibold text-text">{row.name}</p>
                            <p className="truncate text-xs text-text-secondary">
                              {row.description}
                            </p>
                          </div>
                        </div>
                      </td>
                      <td className="px-5 py-3.5">
                        <StatusBadge
                          label={row.typeLabel}
                          tone={typeTone(row.type)}
                        />
                      </td>
                      <td className="px-5 py-3.5 text-text-secondary">
                        {row.dateRangeLabel}
                      </td>
                      <td className="px-5 py-3.5 text-text-secondary">
                        {formatDateTime(row.generatedOn)}
                      </td>
                      <td className="px-5 py-3.5 text-text-secondary">
                        {row.generatedBy}
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="inline-flex items-center gap-1.5 text-text-secondary">
                          <FormatIcon className="size-3.5" aria-hidden />
                          {row.format === 'excel' ? 'Excel' : 'PDF'}
                        </span>
                      </td>
                      <td className="px-5 py-3.5">
                        <div className="flex items-center justify-end gap-1">
                          <button
                            type="button"
                            className="rounded-md p-1.5 text-brand-orange hover:bg-brand-orange/5 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-orange"
                            aria-label={`Download ${row.name}`}
                          >
                            <Download className="size-4" />
                          </button>
                          <button
                            type="button"
                            className="rounded-md p-1.5 text-text-secondary hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-champagne"
                            aria-label={`More actions for ${row.name}`}
                          >
                            <MoreVertical className="size-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <ul className="divide-y divide-border lg:hidden">
            {rows.map((row) => (
              <li key={row.id} className="space-y-2 px-4 py-4">
                <div className="flex items-start justify-between gap-3">
                  <div className="min-w-0">
                    <p className="font-semibold text-text">{row.name}</p>
                    <p className="text-xs text-text-secondary">
                      {row.description}
                    </p>
                  </div>
                  <StatusBadge
                    label={row.typeLabel}
                    tone={typeTone(row.type)}
                  />
                </div>
                <p className="text-xs text-text-secondary">
                  {row.dateRangeLabel} · {formatDateTime(row.generatedOn)}
                </p>
              </li>
            ))}
          </ul>

          <ReportsPagination meta={meta} onPageChange={onPageChange} />
        </>
      )}
    </div>
  );
}
